### PR TITLE
Switching to population level object

### PR DESCRIPTION
**Pull request by LeahPrice**
Changing a population level object rather than a particle level object.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
You are getting close.  This is _almost_ ready.  One issue, though, is that the ChangeLog and the eg the [first R file listed in the commit change](https://github.com/eddelbuettel/rcppsmc/pull/1/files) have a change I already have:

```diff
-    res <- .Call("blockpfGaussianOpt", data, particles, lag, PACKAGE="RcppSMC")
+    res <- .Call("blockpfGaussianOpt_impl", data, particles, lag, PACKAGE="RcppSMC")
```

Are you sure you made the PR against the current version of my master, ie with commit 63bb33d ?

**Comment by LeahPrice** [comment]
I made the PR against the current version of your master, but I think the issue could be the version which I based my code on. I was having trouble getting your most recent commit into my fork so I just made the updates manually. Should I try again to fix that and start a new PR?

**Comment by eddelbuettel** [comment]
As I said before:
- set up ours as parentrepo
- merge from parentrepo

I have this in an old README I keep in my main `~/git/` repo:

```
- add a tracking master (cf https://help.github.com/articles/adding-a-remote)
        git remote add --track master parentrepo https://github.com/bwlewis/rredis.git

- to merge from a tracked parent repo into master (eg r-travis)
	git merge parentrepo/master
```

You can always do `git log` and see if the commits "there" are reflected "here".  If not, then you're not current.

**Comment by eddelbuettel** [comment]
And don't despair.  I had much worse collaborators who would just email altered file.  But these days we have proper tools, and it is better in the medium to long run for all of us to use them.

**Pull request closed without merging**
